/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: zepben/protobuf/hc/opendss/OpenDssReport.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "zepben/protobuf/hc/opendss/OpenDssReport.pb-c.h"
void   open_dss_report__init
                     (OpenDssReport         *message)
{
  static const OpenDssReport init_value = OPEN_DSS_REPORT__INIT;
  *message = init_value;
}
size_t open_dss_report__get_packed_size
                     (const OpenDssReport *message)
{
  assert(message->base.descriptor == &open_dss_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_dss_report__pack
                     (const OpenDssReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_dss_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_dss_report__pack_to_buffer
                     (const OpenDssReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_dss_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenDssReport *
       open_dss_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenDssReport *)
     protobuf_c_message_unpack (&open_dss_report__descriptor,
                                allocator, len, data);
}
void   open_dss_report__free_unpacked
                     (OpenDssReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_dss_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   open_dss_report_batch__init
                     (OpenDssReportBatch         *message)
{
  static const OpenDssReportBatch init_value = OPEN_DSS_REPORT_BATCH__INIT;
  *message = init_value;
}
size_t open_dss_report_batch__get_packed_size
                     (const OpenDssReportBatch *message)
{
  assert(message->base.descriptor == &open_dss_report_batch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_dss_report_batch__pack
                     (const OpenDssReportBatch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_dss_report_batch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_dss_report_batch__pack_to_buffer
                     (const OpenDssReportBatch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_dss_report_batch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenDssReportBatch *
       open_dss_report_batch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenDssReportBatch *)
     protobuf_c_message_unpack (&open_dss_report_batch__descriptor,
                                allocator, len, data);
}
void   open_dss_report_batch__free_unpacked
                     (OpenDssReportBatch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_dss_report_batch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor open_dss_report__field_descriptors[14] =
{
  {
    "di",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, di),
    &demand_interval_report__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phv",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, phv),
    &phase_voltage_report__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ov",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, ov),
    &overload_report__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vr",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, vr),
    &voltage_report__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, sr),
    &summary_report__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "el",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, el),
    &event_log__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tr",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, tr),
    &taps_report__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lr",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, lr),
    &loop_report__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibr",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, ibr),
    &isolated_buses_report__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "le",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, le),
    &losses_entry__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "losses",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, losses),
    &losses_totals__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nm",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, nm),
    &node_mismatch__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kvm",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, kvm),
    &kvbase_mismatch__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "failure",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(OpenDssReport, report_case),
    offsetof(OpenDssReport, failure),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_dss_report__field_indices_by_name[] = {
  0,   /* field[0] = di */
  5,   /* field[5] = el */
  13,   /* field[13] = failure */
  8,   /* field[8] = ibr */
  12,   /* field[12] = kvm */
  9,   /* field[9] = le */
  10,   /* field[10] = losses */
  7,   /* field[7] = lr */
  11,   /* field[11] = nm */
  2,   /* field[2] = ov */
  1,   /* field[1] = phv */
  4,   /* field[4] = sr */
  6,   /* field[6] = tr */
  3,   /* field[3] = vr */
};
static const ProtobufCIntRange open_dss_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor open_dss_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "zepben.protobuf.hc.opendss.OpenDssReport",
  "OpenDssReport",
  "OpenDssReport",
  "zepben.protobuf.hc.opendss",
  sizeof(OpenDssReport),
  14,
  open_dss_report__field_descriptors,
  open_dss_report__field_indices_by_name,
  1,  open_dss_report__number_ranges,
  (ProtobufCMessageInit) open_dss_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor open_dss_report_batch__field_descriptors[1] =
{
  {
    "reports",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenDssReportBatch, n_reports),
    offsetof(OpenDssReportBatch, reports),
    &open_dss_report__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_dss_report_batch__field_indices_by_name[] = {
  0,   /* field[0] = reports */
};
static const ProtobufCIntRange open_dss_report_batch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor open_dss_report_batch__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "zepben.protobuf.hc.opendss.OpenDssReportBatch",
  "OpenDssReportBatch",
  "OpenDssReportBatch",
  "zepben.protobuf.hc.opendss",
  sizeof(OpenDssReportBatch),
  1,
  open_dss_report_batch__field_descriptors,
  open_dss_report_batch__field_indices_by_name,
  1,  open_dss_report_batch__number_ranges,
  (ProtobufCMessageInit) open_dss_report_batch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
