/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: hc/opendss/EnergyMeter.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "hc/opendss/EnergyMeter.pb-c.h"
void   volt_base_registers__init
                     (VoltBaseRegisters         *message)
{
  static const VoltBaseRegisters init_value = VOLT_BASE_REGISTERS__INIT;
  *message = init_value;
}
size_t volt_base_registers__get_packed_size
                     (const VoltBaseRegisters *message)
{
  assert(message->base.descriptor == &volt_base_registers__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t volt_base_registers__pack
                     (const VoltBaseRegisters *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &volt_base_registers__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t volt_base_registers__pack_to_buffer
                     (const VoltBaseRegisters *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &volt_base_registers__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VoltBaseRegisters *
       volt_base_registers__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VoltBaseRegisters *)
     protobuf_c_message_unpack (&volt_base_registers__descriptor,
                                allocator, len, data);
}
void   volt_base_registers__free_unpacked
                     (VoltBaseRegisters *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &volt_base_registers__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   demand_interval_report__init
                     (DemandIntervalReport         *message)
{
  static const DemandIntervalReport init_value = DEMAND_INTERVAL_REPORT__INIT;
  *message = init_value;
}
size_t demand_interval_report__get_packed_size
                     (const DemandIntervalReport *message)
{
  assert(message->base.descriptor == &demand_interval_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t demand_interval_report__pack
                     (const DemandIntervalReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &demand_interval_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t demand_interval_report__pack_to_buffer
                     (const DemandIntervalReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &demand_interval_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DemandIntervalReport *
       demand_interval_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DemandIntervalReport *)
     protobuf_c_message_unpack (&demand_interval_report__descriptor,
                                allocator, len, data);
}
void   demand_interval_report__free_unpacked
                     (DemandIntervalReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &demand_interval_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   max_min_avg__init
                     (MaxMinAvg         *message)
{
  static const MaxMinAvg init_value = MAX_MIN_AVG__INIT;
  *message = init_value;
}
size_t max_min_avg__get_packed_size
                     (const MaxMinAvg *message)
{
  assert(message->base.descriptor == &max_min_avg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t max_min_avg__pack
                     (const MaxMinAvg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &max_min_avg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t max_min_avg__pack_to_buffer
                     (const MaxMinAvg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &max_min_avg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MaxMinAvg *
       max_min_avg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MaxMinAvg *)
     protobuf_c_message_unpack (&max_min_avg__descriptor,
                                allocator, len, data);
}
void   max_min_avg__free_unpacked
                     (MaxMinAvg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &max_min_avg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   phase_voltage_report_values__init
                     (PhaseVoltageReportValues         *message)
{
  static const PhaseVoltageReportValues init_value = PHASE_VOLTAGE_REPORT_VALUES__INIT;
  *message = init_value;
}
size_t phase_voltage_report_values__get_packed_size
                     (const PhaseVoltageReportValues *message)
{
  assert(message->base.descriptor == &phase_voltage_report_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t phase_voltage_report_values__pack
                     (const PhaseVoltageReportValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &phase_voltage_report_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t phase_voltage_report_values__pack_to_buffer
                     (const PhaseVoltageReportValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &phase_voltage_report_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PhaseVoltageReportValues *
       phase_voltage_report_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PhaseVoltageReportValues *)
     protobuf_c_message_unpack (&phase_voltage_report_values__descriptor,
                                allocator, len, data);
}
void   phase_voltage_report_values__free_unpacked
                     (PhaseVoltageReportValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &phase_voltage_report_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   phase_voltage_report__init
                     (PhaseVoltageReport         *message)
{
  static const PhaseVoltageReport init_value = PHASE_VOLTAGE_REPORT__INIT;
  *message = init_value;
}
size_t phase_voltage_report__get_packed_size
                     (const PhaseVoltageReport *message)
{
  assert(message->base.descriptor == &phase_voltage_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t phase_voltage_report__pack
                     (const PhaseVoltageReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &phase_voltage_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t phase_voltage_report__pack_to_buffer
                     (const PhaseVoltageReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &phase_voltage_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PhaseVoltageReport *
       phase_voltage_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PhaseVoltageReport *)
     protobuf_c_message_unpack (&phase_voltage_report__descriptor,
                                allocator, len, data);
}
void   phase_voltage_report__free_unpacked
                     (PhaseVoltageReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &phase_voltage_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   overload_report__init
                     (OverloadReport         *message)
{
  static const OverloadReport init_value = OVERLOAD_REPORT__INIT;
  *message = init_value;
}
size_t overload_report__get_packed_size
                     (const OverloadReport *message)
{
  assert(message->base.descriptor == &overload_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t overload_report__pack
                     (const OverloadReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &overload_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t overload_report__pack_to_buffer
                     (const OverloadReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &overload_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OverloadReport *
       overload_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OverloadReport *)
     protobuf_c_message_unpack (&overload_report__descriptor,
                                allocator, len, data);
}
void   overload_report__free_unpacked
                     (OverloadReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &overload_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   voltage_report_values__init
                     (VoltageReportValues         *message)
{
  static const VoltageReportValues init_value = VOLTAGE_REPORT_VALUES__INIT;
  *message = init_value;
}
size_t voltage_report_values__get_packed_size
                     (const VoltageReportValues *message)
{
  assert(message->base.descriptor == &voltage_report_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t voltage_report_values__pack
                     (const VoltageReportValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &voltage_report_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t voltage_report_values__pack_to_buffer
                     (const VoltageReportValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &voltage_report_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VoltageReportValues *
       voltage_report_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VoltageReportValues *)
     protobuf_c_message_unpack (&voltage_report_values__descriptor,
                                allocator, len, data);
}
void   voltage_report_values__free_unpacked
                     (VoltageReportValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &voltage_report_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   voltage_report__init
                     (VoltageReport         *message)
{
  static const VoltageReport init_value = VOLTAGE_REPORT__INIT;
  *message = init_value;
}
size_t voltage_report__get_packed_size
                     (const VoltageReport *message)
{
  assert(message->base.descriptor == &voltage_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t voltage_report__pack
                     (const VoltageReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &voltage_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t voltage_report__pack_to_buffer
                     (const VoltageReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &voltage_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VoltageReport *
       voltage_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VoltageReport *)
     protobuf_c_message_unpack (&voltage_report__descriptor,
                                allocator, len, data);
}
void   voltage_report__free_unpacked
                     (VoltageReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &voltage_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   energy_meter_report__init
                     (EnergyMeterReport         *message)
{
  static const EnergyMeterReport init_value = ENERGY_METER_REPORT__INIT;
  *message = init_value;
}
size_t energy_meter_report__get_packed_size
                     (const EnergyMeterReport *message)
{
  assert(message->base.descriptor == &energy_meter_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t energy_meter_report__pack
                     (const EnergyMeterReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &energy_meter_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t energy_meter_report__pack_to_buffer
                     (const EnergyMeterReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &energy_meter_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EnergyMeterReport *
       energy_meter_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EnergyMeterReport *)
     protobuf_c_message_unpack (&energy_meter_report__descriptor,
                                allocator, len, data);
}
void   energy_meter_report__free_unpacked
                     (EnergyMeterReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &energy_meter_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor volt_base_registers__field_descriptors[6] =
{
  {
    "vbase",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VoltBaseRegisters, vbase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kvLosses",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VoltBaseRegisters, kvlosses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kvLineLoss",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VoltBaseRegisters, kvlineloss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kvLoadLoss",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VoltBaseRegisters, kvloadloss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kvNoLoadLoss",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VoltBaseRegisters, kvnoloadloss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kvLoadEnergy",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VoltBaseRegisters, kvloadenergy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned volt_base_registers__field_indices_by_name[] = {
  2,   /* field[2] = kvLineLoss */
  5,   /* field[5] = kvLoadEnergy */
  3,   /* field[3] = kvLoadLoss */
  1,   /* field[1] = kvLosses */
  4,   /* field[4] = kvNoLoadLoss */
  0,   /* field[0] = vbase */
};
static const ProtobufCIntRange volt_base_registers__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor volt_base_registers__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VoltBaseRegisters",
  "VoltBaseRegisters",
  "VoltBaseRegisters",
  "",
  sizeof(VoltBaseRegisters),
  6,
  volt_base_registers__field_descriptors,
  volt_base_registers__field_indices_by_name,
  1,  volt_base_registers__number_ranges,
  (ProtobufCMessageInit) volt_base_registers__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor demand_interval_report__field_descriptors[35] =
{
  {
    "element",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, element),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hour",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kwh",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, kwh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kvarh",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, kvarh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxKw",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, maxkw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxKva",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, maxkva),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zoneKwh",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, zonekwh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zoneKvarh",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, zonekvarh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zoneMaxKw",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, zonemaxkw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zoneMaxKva",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, zonemaxkva),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "overloadKwhNormal",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, overloadkwhnormal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "overloadKwhEmerg",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, overloadkwhemerg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadEEN",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, loadeen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadUE",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, loadue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zoneLossesKwh",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, zonelosseskwh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zoneLossesKvarh",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, zonelosseskvarh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zoneMaxKwLosses",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, zonemaxkwlosses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zoneMaxKvarLosses",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, zonemaxkvarlosses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadLossesKwh",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, loadlosseskwh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadLossesKvarh",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, loadlosseskvarh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "noLoadLossesKwh",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, noloadlosseskwh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "noLoadLossesKvarh",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, noloadlosseskvarh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxKwLoadLosses",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, maxkwloadlosses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxKwNoLoadLosses",
    24,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, maxkwnoloadlosses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lineLosses",
    25,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, linelosses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transformerLosses",
    26,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, transformerlosses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lineModeLineLosses",
    27,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, linemodelinelosses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zeroModeLineLosses",
    28,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, zeromodelinelosses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phaseLineLosses3",
    29,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, phaselinelosses3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phaseLineLosses12",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, phaselinelosses12),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "genKwh",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, genkwh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "genKvarh",
    32,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, genkvarh),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "genMaxKw",
    33,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, genmaxkw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "genMaxKva",
    34,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(DemandIntervalReport, genmaxkva),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltBases",
    35,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DemandIntervalReport, n_voltbases),
    offsetof(DemandIntervalReport, voltbases),
    &volt_base_registers__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned demand_interval_report__field_indices_by_name[] = {
  0,   /* field[0] = element */
  31,   /* field[31] = genKvarh */
  30,   /* field[30] = genKwh */
  33,   /* field[33] = genMaxKva */
  32,   /* field[32] = genMaxKw */
  1,   /* field[1] = hour */
  3,   /* field[3] = kvarh */
  2,   /* field[2] = kwh */
  24,   /* field[24] = lineLosses */
  26,   /* field[26] = lineModeLineLosses */
  12,   /* field[12] = loadEEN */
  19,   /* field[19] = loadLossesKvarh */
  18,   /* field[18] = loadLossesKwh */
  13,   /* field[13] = loadUE */
  5,   /* field[5] = maxKva */
  4,   /* field[4] = maxKw */
  22,   /* field[22] = maxKwLoadLosses */
  23,   /* field[23] = maxKwNoLoadLosses */
  21,   /* field[21] = noLoadLossesKvarh */
  20,   /* field[20] = noLoadLossesKwh */
  11,   /* field[11] = overloadKwhEmerg */
  10,   /* field[10] = overloadKwhNormal */
  29,   /* field[29] = phaseLineLosses12 */
  28,   /* field[28] = phaseLineLosses3 */
  25,   /* field[25] = transformerLosses */
  34,   /* field[34] = voltBases */
  27,   /* field[27] = zeroModeLineLosses */
  7,   /* field[7] = zoneKvarh */
  6,   /* field[6] = zoneKwh */
  15,   /* field[15] = zoneLossesKvarh */
  14,   /* field[14] = zoneLossesKwh */
  9,   /* field[9] = zoneMaxKva */
  17,   /* field[17] = zoneMaxKvarLosses */
  8,   /* field[8] = zoneMaxKw */
  16,   /* field[16] = zoneMaxKwLosses */
};
static const ProtobufCIntRange demand_interval_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 35 }
};
const ProtobufCMessageDescriptor demand_interval_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DemandIntervalReport",
  "DemandIntervalReport",
  "DemandIntervalReport",
  "",
  sizeof(DemandIntervalReport),
  35,
  demand_interval_report__field_descriptors,
  demand_interval_report__field_indices_by_name,
  1,  demand_interval_report__number_ranges,
  (ProtobufCMessageInit) demand_interval_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor max_min_avg__field_descriptors[3] =
{
  {
    "max",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(MaxMinAvg, max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(MaxMinAvg, min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avg",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(MaxMinAvg, avg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned max_min_avg__field_indices_by_name[] = {
  2,   /* field[2] = avg */
  0,   /* field[0] = max */
  1,   /* field[1] = min */
};
static const ProtobufCIntRange max_min_avg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor max_min_avg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MaxMinAvg",
  "MaxMinAvg",
  "MaxMinAvg",
  "",
  sizeof(MaxMinAvg),
  3,
  max_min_avg__field_descriptors,
  max_min_avg__field_indices_by_name,
  1,  max_min_avg__number_ranges,
  (ProtobufCMessageInit) max_min_avg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor phase_voltage_report_values__field_descriptors[4] =
{
  {
    "vbase",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(PhaseVoltageReportValues, vbase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phs1",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PhaseVoltageReportValues, phs1),
    &max_min_avg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phs2",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PhaseVoltageReportValues, phs2),
    &max_min_avg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phs3",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PhaseVoltageReportValues, phs3),
    &max_min_avg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned phase_voltage_report_values__field_indices_by_name[] = {
  1,   /* field[1] = phs1 */
  2,   /* field[2] = phs2 */
  3,   /* field[3] = phs3 */
  0,   /* field[0] = vbase */
};
static const ProtobufCIntRange phase_voltage_report_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor phase_voltage_report_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PhaseVoltageReportValues",
  "PhaseVoltageReportValues",
  "PhaseVoltageReportValues",
  "",
  sizeof(PhaseVoltageReportValues),
  4,
  phase_voltage_report_values__field_descriptors,
  phase_voltage_report_values__field_indices_by_name,
  1,  phase_voltage_report_values__number_ranges,
  (ProtobufCMessageInit) phase_voltage_report_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor phase_voltage_report__field_descriptors[3] =
{
  {
    "element",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PhaseVoltageReport, element),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hour",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(PhaseVoltageReport, hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PhaseVoltageReport, n_values),
    offsetof(PhaseVoltageReport, values),
    &phase_voltage_report_values__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned phase_voltage_report__field_indices_by_name[] = {
  0,   /* field[0] = element */
  1,   /* field[1] = hour */
  2,   /* field[2] = values */
};
static const ProtobufCIntRange phase_voltage_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor phase_voltage_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PhaseVoltageReport",
  "PhaseVoltageReport",
  "PhaseVoltageReport",
  "",
  sizeof(PhaseVoltageReport),
  3,
  phase_voltage_report__field_descriptors,
  phase_voltage_report__field_indices_by_name,
  1,  phase_voltage_report__number_ranges,
  (ProtobufCMessageInit) phase_voltage_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor overload_report__field_descriptors[10] =
{
  {
    "hour",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OverloadReport, hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "element",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OverloadReport, element),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normalAmps",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OverloadReport, normalamps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "emergAmps",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OverloadReport, emergamps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "percentNormal",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OverloadReport, percentnormal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "percentEmerg",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OverloadReport, percentemerg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kvBase",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OverloadReport, kvbase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phase1Amps",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OverloadReport, phase1amps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phase2Amps",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OverloadReport, phase2amps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phase3Amps",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OverloadReport, phase3amps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned overload_report__field_indices_by_name[] = {
  1,   /* field[1] = element */
  3,   /* field[3] = emergAmps */
  0,   /* field[0] = hour */
  6,   /* field[6] = kvBase */
  2,   /* field[2] = normalAmps */
  5,   /* field[5] = percentEmerg */
  4,   /* field[4] = percentNormal */
  7,   /* field[7] = phase1Amps */
  8,   /* field[8] = phase2Amps */
  9,   /* field[9] = phase3Amps */
};
static const ProtobufCIntRange overload_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor overload_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OverloadReport",
  "OverloadReport",
  "OverloadReport",
  "",
  sizeof(OverloadReport),
  10,
  overload_report__field_descriptors,
  overload_report__field_indices_by_name,
  1,  overload_report__number_ranges,
  (ProtobufCMessageInit) overload_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor voltage_report_values__field_descriptors[6] =
{
  {
    "underVoltages",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(VoltageReportValues, undervoltages),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minVoltage",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VoltageReportValues, minvoltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "overVoltage",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(VoltageReportValues, overvoltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxVoltage",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VoltageReportValues, maxvoltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minBus",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VoltageReportValues, minbus),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxBus",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VoltageReportValues, maxbus),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned voltage_report_values__field_indices_by_name[] = {
  5,   /* field[5] = maxBus */
  3,   /* field[3] = maxVoltage */
  4,   /* field[4] = minBus */
  1,   /* field[1] = minVoltage */
  2,   /* field[2] = overVoltage */
  0,   /* field[0] = underVoltages */
};
static const ProtobufCIntRange voltage_report_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor voltage_report_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VoltageReportValues",
  "VoltageReportValues",
  "VoltageReportValues",
  "",
  sizeof(VoltageReportValues),
  6,
  voltage_report_values__field_descriptors,
  voltage_report_values__field_indices_by_name,
  1,  voltage_report_values__number_ranges,
  (ProtobufCMessageInit) voltage_report_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor voltage_report__field_descriptors[3] =
{
  {
    "hour",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(VoltageReport, hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hv",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(VoltageReport, hv),
    &voltage_report_values__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lv",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(VoltageReport, lv),
    &voltage_report_values__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned voltage_report__field_indices_by_name[] = {
  0,   /* field[0] = hour */
  1,   /* field[1] = hv */
  2,   /* field[2] = lv */
};
static const ProtobufCIntRange voltage_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor voltage_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VoltageReport",
  "VoltageReport",
  "VoltageReport",
  "",
  sizeof(VoltageReport),
  3,
  voltage_report__field_descriptors,
  voltage_report__field_indices_by_name,
  1,  voltage_report__number_ranges,
  (ProtobufCMessageInit) voltage_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor energy_meter_report__field_descriptors[4] =
{
  {
    "di",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EnergyMeterReport, report_case),
    offsetof(EnergyMeterReport, di),
    &demand_interval_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phv",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EnergyMeterReport, report_case),
    offsetof(EnergyMeterReport, phv),
    &phase_voltage_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ov",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EnergyMeterReport, report_case),
    offsetof(EnergyMeterReport, ov),
    &overload_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vr",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EnergyMeterReport, report_case),
    offsetof(EnergyMeterReport, vr),
    &voltage_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned energy_meter_report__field_indices_by_name[] = {
  0,   /* field[0] = di */
  2,   /* field[2] = ov */
  1,   /* field[1] = phv */
  3,   /* field[3] = vr */
};
static const ProtobufCIntRange energy_meter_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor energy_meter_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EnergyMeterReport",
  "EnergyMeterReport",
  "EnergyMeterReport",
  "",
  sizeof(EnergyMeterReport),
  4,
  energy_meter_report__field_descriptors,
  energy_meter_report__field_indices_by_name,
  1,  energy_meter_report__number_ranges,
  (ProtobufCMessageInit) energy_meter_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
