/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: hc/opendss/QueueMessage.proto */

#ifndef PROTOBUF_C_hc_2fopendss_2fQueueMessage_2eproto__INCLUDED
#define PROTOBUF_C_hc_2fopendss_2fQueueMessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "hc/opendss/EnergyMeter.pb-c.h"
#include "hc/opendss/Diagnostics.pb-c.h"

typedef struct QueueMessage QueueMessage;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  QUEUE_MESSAGE__REPORT__NOT_SET = 0,
  QUEUE_MESSAGE__REPORT_DI = 1,
  QUEUE_MESSAGE__REPORT_PHV = 2,
  QUEUE_MESSAGE__REPORT_OV = 3,
  QUEUE_MESSAGE__REPORT_VR = 4,
  QUEUE_MESSAGE__REPORT_SR = 5,
  QUEUE_MESSAGE__REPORT_EL = 6,
  QUEUE_MESSAGE__REPORT_TR = 7,
  QUEUE_MESSAGE__REPORT_LR = 8,
  QUEUE_MESSAGE__REPORT_IBR = 9,
  QUEUE_MESSAGE__REPORT_LE = 10,
  QUEUE_MESSAGE__REPORT_LOSSES = 11,
  QUEUE_MESSAGE__REPORT_NM = 12,
  QUEUE_MESSAGE__REPORT_KVM = 13
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(QUEUE_MESSAGE__REPORT__CASE)
} QueueMessage__ReportCase;

/*
 **
 * The message type we actually stream, which contains one of the above reports.
 */
struct  QueueMessage
{
  ProtobufCMessage base;
  QueueMessage__ReportCase report_case;
  union {
    DemandIntervalReport *di;
    PhaseVoltageReport *phv;
    OverloadReport *ov;
    VoltageReport *vr;
    SummaryReport *sr;
    EventLog *el;
    TapsReport *tr;
    LoopReport *lr;
    IsolatedBusesReport *ibr;
    LossesEntry *le;
    LossesTotals *losses;
    NodeMismatch *nm;
    KVBaseMismatch *kvm;
  };
};
#define QUEUE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&queue_message__descriptor) \
    , QUEUE_MESSAGE__REPORT__NOT_SET, {0} }


/* QueueMessage methods */
void   queue_message__init
                     (QueueMessage         *message);
size_t queue_message__get_packed_size
                     (const QueueMessage   *message);
size_t queue_message__pack
                     (const QueueMessage   *message,
                      uint8_t             *out);
size_t queue_message__pack_to_buffer
                     (const QueueMessage   *message,
                      ProtobufCBuffer     *buffer);
QueueMessage *
       queue_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   queue_message__free_unpacked
                     (QueueMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*QueueMessage_Closure)
                 (const QueueMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor queue_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_hc_2fopendss_2fQueueMessage_2eproto__INCLUDED */
