/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: hc/opendss/QueueMessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "hc/opendss/QueueMessage.pb-c.h"
void   queue_message__init
                     (QueueMessage         *message)
{
  static const QueueMessage init_value = QUEUE_MESSAGE__INIT;
  *message = init_value;
}
size_t queue_message__get_packed_size
                     (const QueueMessage *message)
{
  assert(message->base.descriptor == &queue_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t queue_message__pack
                     (const QueueMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &queue_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t queue_message__pack_to_buffer
                     (const QueueMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &queue_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueueMessage *
       queue_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueueMessage *)
     protobuf_c_message_unpack (&queue_message__descriptor,
                                allocator, len, data);
}
void   queue_message__free_unpacked
                     (QueueMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &queue_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor queue_message__field_descriptors[13] =
{
  {
    "di",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, di),
    &demand_interval_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phv",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, phv),
    &phase_voltage_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ov",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, ov),
    &overload_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vr",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, vr),
    &voltage_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, sr),
    &summary_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "el",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, el),
    &event_log__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tr",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, tr),
    &taps_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lr",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, lr),
    &loop_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibr",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, ibr),
    &isolated_buses_report__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "le",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, le),
    &losses_entry__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "losses",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, losses),
    &losses_totals__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nm",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, nm),
    &node_mismatch__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kvm",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueueMessage, report_case),
    offsetof(QueueMessage, kvm),
    &kvbase_mismatch__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned queue_message__field_indices_by_name[] = {
  0,   /* field[0] = di */
  5,   /* field[5] = el */
  8,   /* field[8] = ibr */
  12,   /* field[12] = kvm */
  9,   /* field[9] = le */
  10,   /* field[10] = losses */
  7,   /* field[7] = lr */
  11,   /* field[11] = nm */
  2,   /* field[2] = ov */
  1,   /* field[1] = phv */
  4,   /* field[4] = sr */
  6,   /* field[6] = tr */
  3,   /* field[3] = vr */
};
static const ProtobufCIntRange queue_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor queue_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "QueueMessage",
  "QueueMessage",
  "QueueMessage",
  "",
  sizeof(QueueMessage),
  13,
  queue_message__field_descriptors,
  queue_message__field_indices_by_name,
  1,  queue_message__number_ranges,
  (ProtobufCMessageInit) queue_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
