name: Build Zepben Linux libraries

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for lib release'
        required: true
        type: string

jobs:
  find-commit:
    runs-on: ubuntu-latest
    outputs:
      commitID: ${{ steps.find-commit.outputs.commit }}

    steps:
      - uses: actions/checkout@v3

      - name: Work around git permission issue
        run: |
          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
          git config --global --add safe.directory /__w/$dname/$dname
        shell: sh

      - name: Find commit
        id: find-commit
        run: |
          commit=$(git rev-parse --short ${{ github.event.inputs.tag }})
          echo "::set-output name=commit::$(echo $commit)"

  build_linux_x64:
    needs: [find-commit]
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/zepben/dss-capi-builder:latest

    env:
      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.find-commit.outputs.commitID }}



      - name: Build the libraries
        run: |
          make ci
        shell: bash

      - name: Package the libraries
        run: |
          make package
          mv package/dss-libs.bz2 package/dss-libs-${{ needs.find-commit.outputs.commitID }}.bz2
        shell: bash

      - name: Create artefact
        uses: actions/upload-artifact@master
        with:
          name: dss-libs-${{ needs.find-commit.outputs.commitID }}.bz2 
          path: package/dss-libs-${{ needs.find-commit.outputs.commitID }}.bz2 


      - name: Create Release and upload assets
        if: success()
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.find-commit.outputs.commitID }}
          draft: false
          prerelease: false
          files: |
            package/dss-libs-${{ needs.find-commit.outputs.commitID }}.bz2
        continue-on-error: false
